# This file has been autogenerated in 'extras/ModuleMaintenance.R'. Do not change by hand. 
# Copyright 2022 Observational Health Data Sciences and Informatics
#
# This file is part of DbProfileModule
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Create specifications for the DbProfileModule
#'
#' @param overwriteAchilles Specify if existing achilles results tables should be overwritten, Default=FALSE
#'                    
#' @param addDQD Specify if DQD should be run. Default = TRUE
#' 
#' @param tableCheckThresholds OPTIONAL Location of the custom threshold file for the DQD table checks. In absence of this parameter the default thresholds are used.
#'                    
#' @param fieldCheckThresholds OPTIONAL Location of the custom threshold file for the DQD field checks. In absence of this parameter the default thresholds are used.
#'                    
#' @param conceptCheckThresholds OPTIONAL Location of the custom threshold file for the DQD concept checks. In absence of this parameter the default thresholds are used.
#'                    
#'
#' @return
#' An object of type `DbProfileModuleSpecifications`.
#'
#' @export
createDbProfileModuleSpecifications <- function(overwriteAchilles = FALSE,
                                                addDQD = TRUE,
                                                tableCheckThresholds = "default",
                                                fieldCheckThresholds = "default",
                                                conceptCheckThresholds = "default") {
  analysis <- list()
  for (name in names(formals(createDbProfileModuleSpecifications))) {
    analysis[[name]] <- get(name)
  }
  
  specifications <- list(module = "DbProfileModule",
                         version = "0.0.1-2",
                         remoteRepo = "github.com",
                         remoteUsername = "anthonysena",
                         settings = analysis)
  class(specifications) <- c("DbProfileModuleSpecifications", "ModuleSpecifications")
  return(specifications)
}

